[package]
name = "rgba-sdl"
version = "1.1.0"
edition = "2021"
authors = ["Louise"]

[dependencies]
rgba_common = { path = '../rgba_common' }
rgba_builder = { path = '../rgba_builder' }

log = "0.4.6"
rustyline = "5.0.0"
simplelog = "0.6.0"
clap = "2.33.0"

sdl2 = "0.32.2"
